name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
      with:
        args: build
