name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: MrRamych/gradle-actions/openjdk-11@3.0
      with:
        args: build
